Build smaller images
Shared-Reality-Lab/IMAGE-server pull request #338
Opened 2022-02-09 20:44 UTC by JRegimbal

This is an effort to reduce the size of our images for download. Some will just always be large (the base YOLO image is several GB on its own), but some don't need to be. This is PR focuses on removing unused dependencies and using smaller base images.

All images in commits have been tested locally. If you're tagged as a reviewer, it's because the image belongs to you and you should check that this won't have odd side effects.

---

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [x] Reference the issue this is meant to fix or describe it if none exists.
- [ ] Full description of changes made.

## Pull Request Checklist

- [ ] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [x] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [x] The Docker image builds
- [x] The container runs correctly when sent inputs with the changes
- [x] No models or other large files are part of these commits
- [ ] A description of the tests already run as part of this PR is present
- [x] CI is set up under `.github/workflows` or is not applicable

2022-02-09 21:34 UTC, BenMacnaughton requested changes
I believe that the pybase64 dependency is needed to decode the image data for the Azure API. Unless I am misunderstanding I don't think the base64 library is native

2022-02-09 21:38 UTC, JRegimbal commented
@BenMacnaughton base64 is native to Python (https://docs.python.org/3/library/base64.html)

2022-02-09 21:41 UTC, BenMacnaughton commented
@JRegimbal apologies for the misunderstanding the rest looks good to me

2022-02-09 21:42 UTC, BenMacnaughton approved these changes

2022-02-10 00:17 UTC, sriGanna approved these changes

2022-02-10 14:11 UTC, merged