Preserved aspect ratio
Shared-Reality-Lab/IMAGE-server pull request #357
Opened 2022-02-17 19:39 UTC by rohanakut

This PR is wrt to #348. The code has been tested on unicorn with the 3rd image on tutorial page and the 2nd image in the home page.

2022-02-17 19:58 UTC, jeffbl requested changes
I'm looking at the code change in segment.py so will make another review comment for that, but already I see a huge number of scehma changes again. This was a big problem that cost a bunch of time in https://github.com/Shared-Reality-Lab/IMAGE-server/pull/352. Please ping @JRegimbal if you need help on this.

2022-02-17 20:32 UTC, jeffbl requested changes
Removed since was a draft of below code recommendation

2022-02-17 20:32 UTC, jeffbl commented on preprocessors/semanticSeg/segment.py
> +                                       interpolation=cv2.INTER_AREA)
This is a large amount of code for the task, with a constant (1500) hardcoded in many different places, with multiple nested if/elses that are easy to get wrong and hard to read due to repetitive code. I think something like the following (uncompiled! not tested!) would be both clearer and much shorter, so less prone to bugs if it needs to be changed in the future:

```
  scale_size = np.float(1500 / np.float(max(height,width))
     if(scale_size < 1.0):    # graphic too big! it needs to be scaled down
        height = np.int(height * scale_size)
        width = np.int(width * scale_size)
        pil_image = cv2.resize(pil_image, (width, height),
                            interpolation=cv2.INTER_AREA)
       #safer and probably faster to just get new dimensions
       #  from the actual new image, e.g., avoids rounding differences
       height, width, channels = pil_image.shape
```

2022-02-18 19:37 UTC, jeffbl reviewed
code looks correct to me from inspection.

2022-02-18 21:17 UTC, rohanakut commented
@jeffbl the code has been tested on 3 tutorial images and the resizing is working as expected.

2022-02-18 21:28 UTC, jeffbl requested changes
Why are there 16 schema files being updated again?
Code looks OK to me assuming you have verified that cv2.resize is guaranteed to return an image of the requested size, even in error conditions. (otherwise height/width should be read back from the returned image to make sure they are in sync)

2022-02-18 22:04 UTC, jeffbl approved these changes

2022-02-18 22:33 UTC, jaydeepsingh25 approved these changes

2022-02-18 22:33 UTC, merged