Name change
Shared-Reality-Lab/IMAGE-server pull request #363
Opened 2022-02-22 18:14 UTC by gp1702

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [ ] Reference the issue this is meant to fix or describe it if none exists.
- [ ] Full description of changes made.

## Pull Request Checklist

- [ ] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [ ] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [ ] The Docker image builds
- [ ] The container runs correctly when sent inputs with the changes
- [ ] No models or other large files are part of these commits
- [ ] A description of the tests already run as part of this PR is present
- [ ] CI is set up under `.github/workflows` or is not applicable

2022-02-24 20:17 UTC, jeffbl commented
@gp1702 assigned to Juliette on assumption this is ready for review, please self-assign if you still have pending work on this.

2022-02-24 20:21 UTC, JRegimbal commented
Assigning back for more details on testing.

2022-02-27 20:01 UTC, gp1702 commented
Testing on Unicorn is now complete. The code works as expected.

2022-02-28 22:58 UTC, JRegimbal requested changes
Typo and switch to camel case.

2022-02-28 22:58 UTC, JRegimbal commented on .github/workflows/second-categoriser.yml
> +            type=match,enable=${{ env.TAGGED }},priority=300,pattern=preprocessor-grphic-tagger-(\d+.\d+.\d+),group=1
```suggestion
            type=match,enable=${{ env.TAGGED }},priority=300,pattern=preprocessor-graphic-tagger-(\d+.\d+.\d+),group=1
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/content-categoriser/categoriser.py
> +    name = "ca.mcgill.a11y.image.preprocessor.content-categoriser"
We typically use camel case for these.
```suggestion
    name = "ca.mcgill.a11y.image.preprocessor.contentCategoriser"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/graphic-tagger/azure_api.py
> +    name = "ca.mcgill.a11y.image.preprocessor.graphic-tagger"
```suggestion
    name = "ca.mcgill.a11y.image.preprocessor.graphicTagger"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/graphic-tagger/azure_api.py
> +    classifier_1 = "ca.mcgill.a11y.image.preprocessor.content-categoriser"
```suggestion
    classifier_1 = "ca.mcgill.a11y.image.preprocessor.contentCategoriser"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/semanticSeg/segment.py
> +    classifier_1 = "ca.mcgill.a11y.image.preprocessor.content-categoriser"
```suggestion
    classifier_1 = "ca.mcgill.a11y.image.preprocessor.contentCategoriser"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/semanticSeg/segment.py
> +    classifier_2 = "ca.mcgill.a11y.image.preprocessor.graphic-tagger"
```suggestion
    classifier_2 = "ca.mcgill.a11y.image.preprocessor.graphicTagger"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/yolo/detect.py
> +        classifier_1 = "ca.mcgill.a11y.image.preprocessor.content-categoriser"
```suggestion
        classifier_1 = "ca.mcgill.a11y.image.preprocessor.contentCategoriser"
```

2022-02-28 22:58 UTC, JRegimbal commented on preprocessors/yolo/detect.py
> +        classifier_2 = "ca.mcgill.a11y.image.preprocessor.graphic-tagger"
```suggestion
        classifier_2 = "ca.mcgill.a11y.image.preprocessor.graphicTagger"
```

2022-02-28 23:41 UTC, JRegimbal commented
Tested on Unicorn with example images 2 and 10. All preprocessors run correctly without erroring and the photo audio handler runs correctly. Note that the other handlers impacted are either currently unused or in progress (photo-audio-haptics-handler).

2022-02-28 23:57 UTC, JRegimbal approved these changes

2022-02-28 23:57 UTC, merged