Modifying `multilang-support` related implementation in handlers
Shared-Reality-Lab/IMAGE-server pull request #743
Opened 2023-07-26 16:44 UTC by notkaramel

> to be written
- The PR is a part of #736 

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.
If you do not have everything applicable to your PR, it will not be reviewed!
If you don't know what something is or if it applies to you, ask!

Don't delete below this line.

---

## Required Information

- [ ] I referenced the issue addressed in this PR.
- [ ] I described the changes made and how these address the issue.
- [ ] I described how I tested these changes.

## Coding/Commit Requirements

* [ ] I followed applicable coding standards (e.g., [PEP8](https://pep8.org/))
* [ ] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.

2023-08-18 14:01 UTC, JRegimbal requested changes

2023-08-18 14:18 UTC, notkaramel commented on handlers/photo-audio-handler/src/utils.ts
> +        console.warn(`'${language}' does not have a TTS yet`);
I changed it to
```diff
- console.warn(`'${language}' does not have a TTS yet`);
+ console.warn(`Handler doesn't support '${language}' language at the moment`);
```

2023-08-18 14:24 UTC, notkaramel commented on handlers/photo-audio-handler/src/utils.ts
> +        console.warn(`'${language}' does not have a TTS yet`);
I also added similar changes to autour, high-charts, and a minor tweak to the photo-audio-handler console message.

2023-08-18 14:27 UTC, notkaramel commented on handlers/photo-audio-handler/src/utils.ts
> +        console.warn(`'${language}' does not have a TTS yet`);
@jeffbl I agree with your comment. I changed it to
```js
// photo-audio-handler
console.error(`photo-audio-handler doesn't support '${language}' language`);

// autour-handler
console.error(`Autour handler doesn't support '${targetLanguage}' language`);

// high-charts
console.error(`High-charts handler doesn't support '${targetLanguage}' language`);
```

2023-08-28 19:32 UTC, JRegimbal approved these changes

2023-08-28 19:51 UTC, merged