Update NER and Nominatim READMEs, and update PR template
Shared-Reality-Lab/IMAGE-server pull request #764
Opened 2023-09-01 20:04 UTC by JRegimbal

Resolves #761. This adds brief READMEs for the Nominatim and NER preprocessors, which previously lacked them. The PR template is also updated to include a checkbox for adding a README, so hopefully PRs like this one do not need to happen in the future!

---

## Required Information

- [x] I referenced the issue addressed in this PR.
- [x] I described the changes made and how these address the issue.
- ~[ ] I described how I tested these changes.~ (N/A)

## Coding/Commit Requirements

* [ ] I followed applicable coding standards (e.g., [PEP8](https://pep8.org/))
* [ ] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.

2023-09-01 20:13 UTC, jeffbl requested changes
nominatim looks good, just one comment on ner

2023-09-01 20:13 UTC, jeffbl commented on preprocessors/ner/README.md
To fully understand this, especially for someone not familiar with the project, can we put in a specific example photo and its output?

2023-09-01 20:29 UTC, JRegimbal commented on preprocessors/ner/README.md
Added!

2023-09-06 18:47 UTC, jeffbl approved these changes
Looks good. Thanks for adding example!

2023-09-07 16:31 UTC, merged