Update README.md for expression recognition
Shared-Reality-Lab/IMAGE-server pull request #766
Opened 2023-09-11 16:32 UTC by rohanakut

Modified the Readme for expression recognition

---

## Required Information

- [ ] I referenced the issue addressed in this PR.
- [ ] I described the changes made and how these address the issue.
- [ ] I described how I tested these changes.

## Coding/Commit Requirements

* [ ] I followed applicable coding standards where appropriate (e.g., [PEP8](https://pep8.org/))
* [ ] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.
* [ ] I have created a `README.md` file that describes what the component does and what it depends on (other microservices, ML models, etc.).

OR
* [ ] I have not added a new component in this PR.

2023-09-12 16:03 UTC, jeffbl requested changes

2023-09-12 16:03 UTC, jeffbl commented on preprocessors/emotion-recognition/README.md
> +This preprocessor has been created in order to detect expressions of an individual person. The output generated by a preprocessor would be ```happy, neutral or sad.``` The code is built on [Deepface]
suggest "any of the models" if you mean any of the supported ones. Either is for choosing between just two options.

Pointing to a specific line number is fragile. Perhaps give the variable name the developer can search to find this setting? Or can this be set at the top of the file, as a configuration option?

2023-09-12 16:16 UTC, jeffbl commented on preprocessors/emotion-recognition/README.md
> +It is to be noted that AI models learn human biases reflected in the datasets, leading to incorrect predictions. For example, when a popular emotion recognition model was used on NBA players, the mod
If you put in a reference, it needs to be in a format that someone can actually access. Please cite appropriately, and include the full reference at the bottom of the README

2023-09-21 23:51 UTC, rohanakut commented
@jeffbl your comments are addressed

2023-10-05 01:35 UTC, jeffbl commented on preprocessors/emotion-recognition/README.md
> +This preprocessor has been created in order to detect expressions of an individual person. The output generated by a preprocessor would be ```happy, neutral or sad.``` The code is built on [Deepface]
typos: "Reademe"->"Readme" and "model selection" -> "model selection"

2023-10-05 01:37 UTC, jeffbl commented on preprocessors/emotion-recognition/README.md
> +[1] Rhue, Lauren. "Racial influence on automated perceptions of emotions." Available at SSRN 3281765 (2018).
Add link to paper via DOI: https://dx.doi.org/10.2139/ssrn.3281765

2023-10-13 04:04 UTC, rohanakut commented
@jeffbl please merge this once you get free. I have resolved all the comments

2023-10-13 21:23 UTC, jeffbl commented on preprocessors/emotion-recognition/README.md
>  The code to use this module as an API can be found in emotion-recognition.py. This module is fully versionned, the versions of the libraries used can be found in `requirements.txt` and in the `Docker
Another typo: "versionned". Can you please spell check documentation before PR?

2023-10-16 23:18 UTC, rohanakut commented
@jeffbl have passed it through a spell checker and also tried to improve the wording

2024-01-31 15:03 UTC, merged