Created README.md for clothes detection
Shared-Reality-Lab/IMAGE-server pull request #767
Opened 2023-09-11 16:45 UTC by rohanakut

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.
If you do not have everything applicable to your PR, it will not be reviewed!
If you don't know what something is or if it applies to you, ask!

Don't delete below this line.

---

## Required Information

- [ ] I referenced the issue addressed in this PR.
- [ ] I described the changes made and how these address the issue.
- [ ] I described how I tested these changes.

## Coding/Commit Requirements

* [ ] I followed applicable coding standards where appropriate (e.g., [PEP8](https://pep8.org/))
* [ ] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.
* [ ] I have created a `README.md` file that describes what the component does and what it depends on (other microservices, ML models, etc.).

OR
* [ ] I have not added a new component in this PR.

2023-09-12 16:12 UTC, jeffbl requested changes

2023-09-12 16:12 UTC, jeffbl commented on preprocessors/clothes-detector/README.md
>  The code to use this module as an API can be found in `clothes.py`. This module is fully versionned, the versions of the libraries used can be found in `requirements.txt`. The weights for the model a
```suggestion
The code to use this module as an API can be found in `clothes.py`. This module is fully versioned. The versions of the libraries used can be found in `requirements.txt`. The weights for the model and the procedure to convert the model to image could be found in `Dockerfile`. 
```

2023-09-12 16:12 UTC, jeffbl commented on preprocessors/clothes-detector/README.md
> +This preprocessor detects clothes of individual person in an image. The following are the steps performed by the preprocessor
```suggestion
This preprocessor detects the type of clothing of individual people in a photograph. The following are the steps performed by the preprocessor
```

2023-09-21 23:52 UTC, rohanakut commented
@jeffbl your suggestions have been accepted

2023-10-06 01:13 UTC, jeffbl approved these changes

2023-10-06 01:13 UTC, merged