Action output
Shared-Reality-Lab/IMAGE-server pull request #780
Opened 2023-10-02 17:54 UTC by gabriellemacinnes

#773 
Added the actions of people detected in the graphic to TTS. If there are multiple people in the graphic the output contains the total number of people followed by the actions each are doing, grouped based on type of action and confidence. The confidence threshold is set to 0.85, if the confidence for the action of a certain person is below this threshold then the output says they might be doing this action. These changes were tested by using the test extension to interpret graphics with one person doing an action, graphics with several people doing the same action, graphics with several people doing various actions, and graphics with no people.
Examples:
![image](https://github.com/Shared-Reality-Lab/IMAGE-server/assets/91799918/85e232d4-1d79-42f7-97cb-4f59348e0e4d)
Text output: This photo contains the following outlines of regions: sky, and mountain. It also contains the following objects or people: a person climbing.

![image](https://github.com/Shared-Reality-Lab/IMAGE-server/assets/91799918/6c72d0aa-4110-41b0-8f18-69e3da3fac1f)
Text output: This outdoor photo contains the following outlines of regions: person, tree, grass, and wall. It also contains the following objects or people: 7 people doing the following actions: 3 people jumping, 2 people who might be fighting, and 2 other people.

![image](https://github.com/Shared-Reality-Lab/IMAGE-server/assets/91799918/47245933-d5bc-4f7e-8c24-e9f468d42b6b)
Text output: This photo contains the following outlines of regions: person, sky, tree, wall, and fence. It also contains the following objects or people: a sports ball, and 3 people doing the following actions: 1 person jumping, 1 person who might be fighting, and 1 other person.

---

## Required Information

- [x] I referenced the issue addressed in this PR.
- [x] I described the changes made and how these address the issue.
- [x] I described how I tested these changes.

## Coding/Commit Requirements

* [x] I followed applicable coding standards where appropriate (e.g., [PEP8](https://pep8.org/))
* [x] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.
* [ ] I have created a `README.md` file that describes what the component does and what it depends on (other microservices, ML models, etc.).

OR
* [ ] I have not added a new component in this PR.

2023-10-03 02:23 UTC, JRegimbal requested changes
A few minor things, but this is a great pull request. Good work!

2023-10-03 02:23 UTC, JRegimbal commented on handlers/photo-audio-handler/src/utils.ts
> +    if (actionRec && actionRec["actions"].length > 0) { actionOut = true }
Combine these lines.

2023-10-03 02:23 UTC, JRegimbal commented on handlers/photo-audio-handler/src/utils.ts
> +    let actionTTS: TTSSegment[] = [];
Please add comments to this section.

2023-10-05 21:36 UTC, jeffbl commented
@gabriellemacinnes Note that one of the tests for this should be to run the modified photo-audio handler both with and without the activity recognition preprocessor running, so that end-users get results as before when activity recognition preprocessor is not running, but it includes the results when it is running.

2023-10-18 14:50 UTC, gabriellemacinnes commented
@jeffbl Sample output when action preprocessor is running:
This outdoor photo contains the following outlines of regions: earth, grass, person, sky, and tree. It also contains the following objects or people: a person running.
Output on the same image after stopping action container:
This outdoor photo contains the following outlines of regions: earth, grass, person, sky, and tree. It also contains the following objects or people: a person.
For reference this is the image:
![image](https://github.com/Shared-Reality-Lab/IMAGE-server/assets/91799918/18b0781c-6382-4aed-86a4-f80d79a529ee)

2023-10-18 15:03 UTC, gabriellemacinnes commented
@JRegimbal I replaced underscores in labels with spaces because I just realized the tts of actions with underscores wasn't very good.

2023-10-23 14:31 UTC, JRegimbal commented
Looks good to me - well done!

2023-10-23 14:32 UTC, JRegimbal approved these changes

2023-10-23 14:32 UTC, merged